CREATE TABLE [dbo].[Utilities]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(MAX) NOT NULL,
	[Price] INT NOT NULL,
	[UnitName] NVARCHAR(MAX) NOT NULL,
	PRIMARY KEY CLUSTERED ([Id] ASC)
)
